### ISSUE TITLE
Add Benchmarks

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-arrow#2]
Since one of the main motivations for using `ZArrow` as opposed to `ZIO` is for performance we should add benchmarks demonstrating the performance improvement. We can start with the benchmarks from before zio/zio#2732 and build from there. We should also publish the results somewhere.

**Comment by tampler** [comment]
I think this closes this issue: https://github.com/zio/zio-arrow/pull/14

**Comment by adamgfraser** [comment]
Agreed.
