### ISSUE TITLE
Alphabetize All Methods

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-arrow#21]
We should alphabetize methods in standard ZIO style to make it easier for users and contributors to find. Typical order is

1. Public abstract defs / vals listed first, and alphabetized, with operators appearing before names.
2. Public concrete defs / vals listed second, and alphabetized, with operators appearing before names.
3. Private implementation details listed third, and alphabetized, with operators appearing before names.

**Comment by jorge-vasquez-2301** [comment]
Hi @adamgfraser, I could take this one as my first contribution 😃
